type storm2={
    id:number;
    sid:number;
    promo:string;
    heading:string;
    keywords:string;
    secheading:string;
    secpara:string;
    text:string;
}

export const maindata2:storm2[]=[

    {
    id:1,
    sid:11,
    promo:"Email Append",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:1,
    sid:12,
    promo:"Data Append",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:1,
    sid:13,
    promo:"Data Verification",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:1,
    sid:14,
    promo:"Data Profiling",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:1,
    sid:15,
    promo:"Data Cleansing",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:2,
    sid:16,
    promo:"Email Campaigns",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:2,
    sid:17,
    promo:"LinkedIn Campaigns",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:2,
    sid:18,
    promo:"LinkedIn Account Management",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:3,
    sid:19,
    promo:"B2B Lead Generation",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:3,
    sid:41,
    promo:"B2C Lead Generation", 
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:4,
    sid:20,
    promo:"CEO Email List",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:4,
    sid:21,
    promo:"CTO Email List",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:4,
    sid:22,
    promo:"HR Email List",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:4,
    sid:23,
    promo:"CMO Email List",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:4,
    sid:24,
    promo:"CHRO Email List",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:5,
    sid:25,
    promo:"E-Commerce Store Setup",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:5,
    sid:26,
    promo:"Product Listing & Catalogue Management",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:5,
    sid:27,
    promo:"E-Commerce Marketing",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:5,
    sid:28,
    promo:"Order Process Tracking",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:5,
    sid:29,
    promo:"Customer Ticket Management",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:6,
    sid:30,
    promo:"Cross Browser Testing",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:6,
    sid:31,
    promo:"End to End Functional Testing",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:6,
    sid:32,
    promo:"Non Functional Testing",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:7,
    sid:33,
    promo:"Live Chat Support",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:7,
    sid:34,
    promo:"Email Support",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:7,
    sid:35,
    promo:"Self-Service Support",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:7,
    sid:36,
    promo:"Interactive Voice Support",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:7,
    sid:37,
    promo:"Social Media Support",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:7,
    sid:38,
    promo:"Web Commerce Support",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:7,
    sid:39,
    promo:"On-Site Support",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },
    {
    id:7,
    sid:40,
    promo:"Telephone Support",
    heading:"string",
    keywords:"string",
    secheading:"string",
    secpara:"string",
    text:"string",
    },

]