type mdata={
    id:number;
    sid:number;
    title:string;
    metakeywords:string;
    description:string;
    
}
export const mdata:mdata[]=[

    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
    {
            id:1,
            sid:11,
            title:"tring",
            metakeywords:"tring",
            description:"tring",
    },
]